---
title: "Plots for Lecture 2"
author: "Marton Kovacs"
date: '2018 szeptember 14 '
output: html_document
---

# Loading packages
```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(scales)
# library(readr) # Already loadeing with tidyverse
```

# Source sentiment proportion analysis

```{r, echo=FALSE, message=FALSE}
source("calculate_sentiment.r")
```

# Loading the dataset
```{r, message=FALSE}
tmp <- tempfile(fileext = ".zip")
download.file(url = "https://github.com/rudeboybert/JSE_OkCupid/raw/master/profiles.csv.zip", destfile = tmp)
okcupid_raw <- read_csv(tmp)
unlink(tmp)
```

# General Theme
```{r}
th <- theme(panel.background = element_blank(),
            panel.grid.minor = element_blank(),
            axis.line = element_line(color = "black"),
            axis.ticks = element_line(color = "black"))
```

# Variable transformation
```{r}
okcupid <- 
  okcupid_raw %>% 
  mutate(height = height * 2.54,
         income = case_when(income == -1 ~ NA_integer_),
         sex = case_when(sex == "m" ~ "male",
                         sex == "f" ~ "female")) %>% 
  calculate_sentiment(essay0)
```

# Barplot: Smokes
```{r}
okcupid %>% 
  ggplot(aes(smokes)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) + 
  scale_y_continuous(expand = c(0,0), labels=scales::percent) +
  labs(title = "Barplot: Proportion of smokers", 
       x = "Smoking Types", 
       y = "Relative Frequencies") +
  th
```

# Lollipop: body_type
```{r}
okcupid %>%
  group_by(body_type) %>% 
  summarise(body_type_count = n()) %>%
  arrange(body_type_count) %>% 
  mutate(body_type = factor(body_type, body_type)) %>%
  ggplot() +
    aes(x = body_type, y = body_type_count) +
    geom_segment(aes(xend = body_type, 
                     y = 0, 
                     yend = body_type_count)) +
    geom_point(size = 8, 
               color = "orange") +
    labs(title = "Lollipop plot: Body type",
         x = "Body Type", 
         y = "Count") +
    coord_flip() +
    theme_minimal()

```

# Pie Chart: Drug use
```{r}
okcupid %>%
  # filter(!is.na(drugs)) %>%
  count(drugs) %>% 
  ggplot() +
  aes(x = 1, y = n, fill = drugs) +
  geom_col() +
  coord_polar(theta = "y", 
              direction = -1) +
  scale_fill_brewer("Drug use",
                    palette = "Dark2", 
                    na.value = "grey80") +
  theme_void() +
  labs(title = "Pie chart of drug use in the sample")
```

# Waffle plot: Drug use
```{r}
if (!require(waffle)) install.packages(waffle)
library(waffle)

drugs_df <-
        okcupid %>% 
        # drop_na(drugs) %>% 
        count(drugs) %>% 
        mutate(n = (n/sum(n) * 100) %>% round())

drugs_df %>% 
        pull(n) %>% 
        set_names(pull(drugs_df, drugs)) %>% 
        waffle() +
        ggtitle("Waffle plot of drug use in the sample")
```


# Histrogram: Height
```{r, message=FALSE, error=FALSE}
okcupid %>%
  filter(!is.na(height)) %>% 
  ggplot(., aes(height)) +
  geom_histogram(fill = "purple", alpha = .5) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(limits = c(140, 220)) +
  labs(x = "Height", y = "Count") +
  theme_minimal()
```

# Frequency plot: Height x sex
```{r, message=FALSE, error=FALSE}
okcupid %>%
  ggplot() +
  aes(x = height, color = sex) +
  geom_freqpoly(size = 1.2) +
  scale_x_continuous(limits = c(140, 220)) +
  labs(x = "Height", y = "Count") +
  theme_minimal()
```

# Density: age
```{r}
okcupid %>% 
  ggplot() +
  aes(x = age) +
  geom_density(fill = "purple", alpha = .5) +
  labs(x = "Age", y = "Probability density") +
  theme_minimal() +
  ggtitle("Density plot for age")
```

# Boxplot: Age x Sex
```{r}
okcupid %>%
  ggplot() + 
  aes(x = sex, y = age, fill = sex) +
  geom_boxplot(outlier.alpha = .5) +
  theme_minimal() +
  ggtitle("Boxpolot for age by sex")

```

# Heatmap: Drinking x employment
```{r}
drinks_job <- 
  okcupid %>%
  # drop_na(job, drinks) %>%
  mutate(drinks = factor(drinks, 
                         levels =  c("not at all",
                                     "rarely",
                                     "socially",
                                     "often",
                                     "very often",
                                     "desperately"))) %>%
  count(drinks, job)


drinks_job %>% 
  ggplot() +
  aes(x = drinks, y = fct_rev(job), fill = n, label = n) +
  geom_tile() +
  # geom_text(alpha = .5) +
  scale_fill_gradient(low = "white", high = "steelblue") +
  theme_minimal() +
  labs(title = "Heatmap: Drinking x employment ",
       y = "Job",
       x = "Drinking",
       fill = "Number of cases")
```

# Stacked Barplot
```{r}
drinks_job %>% 
  ggplot() +
  aes(x = fct_rev(job), y = n, fill = drinks) +
  geom_col(position = "fill") +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_brewer(palette = "Dark2", 
                    na.value = "grey80") +      
  coord_flip() +
  labs(title = "Stacked barplot: Drinking and employment",
       x = "Jobs",
       y = NULL,
       fill = "Drinks") +
  th
  
  
```