---
title: "3rd_lecture_plots"
author: "Marton Kovacs"
date: '2018 szeptember 20 '
output: html_document
---

# Loading packages
```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(scales)
library(tidytext)
library(ggthemr)
# library(readr) # Already loading with tidyverse
```

# Source sentiment proportion analysis

```{r, echo=FALSE, message=FALSE}
source("calculate_sentiment.r")
```

# Loading the dataset
```{r, message=FALSE}
tmp <- tempfile(fileext = ".zip")
download.file(url = "https://github.com/rudeboybert/JSE_OkCupid/raw/master/profiles.csv.zip", destfile = tmp)
okcupid_raw <- read_csv(tmp)
unlink(tmp)
```

# General Theme
```{r}
ggthemr("grass")
```

# Variable transformation
```{r}
okcupid <- 
  okcupid_raw %>% 
  mutate(height = height * 2.54,
         income = case_when(income == -1 ~ NA_integer_,
                            TRUE ~ income),
         sex = case_when(sex == "m" ~ "male",
                         sex == "f" ~ "female"))

okcupid <-  calculate_sentiment(okcupid, essay0)
```


# Grouped Barplot: drinks x sex
```{r}
okcupid %>%
        mutate(drinks = factor(drinks, 
                        levels =  c("not at all",
                                    "rarely",
                                    "socially",
                                    "often",
                                    "very often",
                                    "desperately"))) %>%
        ggplot() +
        aes(drinks, fill = sex) +
        geom_bar(position = "dodge") +
        scale_y_continuous(expand = c(0,0), limits = c(0, 25000)) +
        labs(title = "Grouped Barplot: Drinking Habits Between Genders",
             fill = "Genders",
             x = "Drinking Types",
             y = "Count")
        
```
