---
title: "Plots"
author: "Marton Kovacs"
date: '2018 szeptember 14 '
output: html_document
---

# Loading packages
```{r setup, echo=FALSE, message=FALSE}
library(scales)
library(tidyverse)
library(readr)
```

# Source sentiment proportion analysis

```{r, echo=FALSE, message=FALSE}
source("calculate_sentiment.r")
```

# Loading the dataset
```{r, message=FALSE}
tmp <- tempfile(fileext = ".zip")
download.file(url = "https://github.com/rudeboybert/JSE_OkCupid/raw/master/profiles.csv.zip", destfile = tmp)
okcupid_raw <- read_csv(tmp)
unlink(tmp)
```

# General Theme
```{r}
th <- theme(panel.background = element_blank(),
            panel.grid.minor = element_blank(),
            axis.line = element_line(color = "black"),
            axis.ticks = element_line(color = "black"))
```

# Variable transformation
```{r}
okcupid <- okcupid_raw %>% 
  mutate(height = height * 2.54,
         income = case_when(income == -1 ~ NA_integer_),
         sex = case_when(sex == "m" ~ "male",
                         sex == "f" ~ "female"))

okcupid <-  calculate_sentiment(okcupid, essay3)
```

# Barplot: Smokes
```{r}
okcupid %>% 
  ggplot(., aes(smokes)) +
  geom_bar(aes(y = (..count..)/sum(..count..))) + 
  scale_y_continuous(expand = c(0,0), labels=scales::percent) +
  labs(x = "Smoking Types", y = "Relative Frequencies") +
  th
```

# Lollipop: body_type
```{r}
okcupid %>%
  group_by(body_type) %>% 
  summarise(body_type_count = n()) %>%
  arrange(body_type_count) %>% 
  mutate(body_type=factor(body_type,body_type)) %>%
ggplot(., aes(body_type, body_type_count)) +
    geom_segment(aes(x=body_type, xend=body_type, y=0, yend=body_type_count)) +
    scale_y_continuous(expand = c(0,0), limits = c(0,16000)) +
    geom_point(size=4, color="orange", alpha=0.7) +
    labs(x = "Body Type", y = "Count") +
    coord_flip() +
    theme_light() +
    theme(
    legend.position="none",
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_line(color = "black"))

```

# Pie Chart: Drugs
```{r}
okcupid %>%
  filter(drugs != "NA") %>% 
  group_by(drugs) %>% 
  summarise(drugs_count = n()) %>% 
  ggplot(., aes("", drugs_count, fill = drugs)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  scale_fill_brewer(palette="Dark2",name = "Drug Usage Rate") +
  theme_minimal() +
  theme(axis.title = element_blank())
```

# Histrogram: Height
```{r, message=FALSE, error=FALSE}
okcupid %>%
  filter(!is.na(height)) %>% 
  ggplot(., aes(height)) +
  geom_histogram() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(limits = c(140, 220)) +
  labs(x = "Height", y = "Count") +
  theme_minimal() +
  theme(axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = "black"))
```

# Density
```{r}
okcupid %>% 
  filter(!is.na(height)) %>% 
  ggplot(., aes(height)) +
  geom_density() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(limits = c(140, 220)) +
  labs(x = "Height", y = "Count") +
  theme_minimal() +
  theme(axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = "black"))
```

# Boxplot: Height
```{r}
okcupid %>%
  filter(!is.na(height),
         height > 56) %>% # Height of the smallest person on Earth accorrding to Guiness World Record 2012
  ggplot(., aes("", height)) + 
  geom_boxplot(outlier.colour = "black", outlier.shape=16,
             outlier.size=2, notch=FALSE) +
  coord_flip() +
  theme_light() +
  theme(axis.title.y = element_blank())

```

# Heatmap: 
```{r}
okcupid %>%
  filter(drinks != "NA") %>% 
  mutate(drinks = as.factor(drinks),
         drinks = fct_relevel(drinks, "not at all",
                              "rarely",
                              "socially",
                              "often",
                              "very often",
                              "desperately")) %>%
  group_by(drinks, job) %>% 
  summarise(count = n()) %>% 
  ggplot(., aes(drinks, job)) +
  geom_tile(aes(fill = count), color = "white") +
  scale_fill_gradient(low = "white", high = "steelblue") +
  scale_x_discrete("", expand = c(0, 0)) + 
  scale_y_discrete("", expand = c(0, 0)) + 
  theme_grey(base_size = 9) + 
  theme(axis.ticks = element_blank())
```

# Stacked Barplot
```{r}

```